/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NavigationImport } from './routes/navigation'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthRankingsImport } from './routes/_auth/rankings'
import { Route as AuthQuestsImport } from './routes/_auth/quests'
import { Route as AuthMarketplaceImport } from './routes/_auth/marketplace'
import { Route as AuthMainnavImport } from './routes/_auth/mainnav'
import { Route as AuthInventoryImport } from './routes/_auth/inventory'
import { Route as AuthHomeImport } from './routes/_auth/home'
import { Route as AuthGuildsImport } from './routes/_auth/guilds'
import { Route as AuthForgingImport } from './routes/_auth/forging'
import { Route as AuthCharacterSidebarImport } from './routes/_auth/_characterSidebar'
import { Route as AuthTeamfightIdImport } from './routes/_auth/teamfight/$id'
import { Route as AuthExploreCharacterIdImport } from './routes/_auth/explore/character/$id'
import { Route as AuthCharacterSidebarCharacterRollImport } from './routes/_auth/_characterSidebar/character/roll'
import { Route as AuthCharacterSidebarCharacterIdImport } from './routes/_auth/_characterSidebar/character/$id'

// Create/Update Routes

const NavigationRoute = NavigationImport.update({
  path: '/navigation',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRankingsRoute = AuthRankingsImport.update({
  path: '/rankings',
  getParentRoute: () => AuthRoute,
} as any)

const AuthQuestsRoute = AuthQuestsImport.update({
  path: '/quests',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMarketplaceRoute = AuthMarketplaceImport.update({
  path: '/marketplace',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMainnavRoute = AuthMainnavImport.update({
  path: '/mainnav',
  getParentRoute: () => AuthRoute,
} as any)

const AuthInventoryRoute = AuthInventoryImport.update({
  path: '/inventory',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHomeRoute = AuthHomeImport.update({
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)

const AuthGuildsRoute = AuthGuildsImport.update({
  path: '/guilds',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgingRoute = AuthForgingImport.update({
  path: '/forging',
  getParentRoute: () => AuthRoute,
} as any)

const AuthCharacterSidebarRoute = AuthCharacterSidebarImport.update({
  id: '/_characterSidebar',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTeamfightIdRoute = AuthTeamfightIdImport.update({
  path: '/teamfight/$id',
  getParentRoute: () => AuthRoute,
} as any)

const AuthExploreCharacterIdRoute = AuthExploreCharacterIdImport.update({
  path: '/explore/character/$id',
  getParentRoute: () => AuthRoute,
} as any)

const AuthCharacterSidebarCharacterRollRoute =
  AuthCharacterSidebarCharacterRollImport.update({
    path: '/character/roll',
    getParentRoute: () => AuthCharacterSidebarRoute,
  } as any)

const AuthCharacterSidebarCharacterIdRoute =
  AuthCharacterSidebarCharacterIdImport.update({
    path: '/character/$id',
    getParentRoute: () => AuthCharacterSidebarRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/navigation': {
      preLoaderRoute: typeof NavigationImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_characterSidebar': {
      preLoaderRoute: typeof AuthCharacterSidebarImport
      parentRoute: typeof AuthImport
    }
    '/_auth/forging': {
      preLoaderRoute: typeof AuthForgingImport
      parentRoute: typeof AuthImport
    }
    '/_auth/guilds': {
      preLoaderRoute: typeof AuthGuildsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/home': {
      preLoaderRoute: typeof AuthHomeImport
      parentRoute: typeof AuthImport
    }
    '/_auth/inventory': {
      preLoaderRoute: typeof AuthInventoryImport
      parentRoute: typeof AuthImport
    }
    '/_auth/mainnav': {
      preLoaderRoute: typeof AuthMainnavImport
      parentRoute: typeof AuthImport
    }
    '/_auth/marketplace': {
      preLoaderRoute: typeof AuthMarketplaceImport
      parentRoute: typeof AuthImport
    }
    '/_auth/quests': {
      preLoaderRoute: typeof AuthQuestsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/rankings': {
      preLoaderRoute: typeof AuthRankingsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/teamfight/$id': {
      preLoaderRoute: typeof AuthTeamfightIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_characterSidebar/character/$id': {
      preLoaderRoute: typeof AuthCharacterSidebarCharacterIdImport
      parentRoute: typeof AuthCharacterSidebarImport
    }
    '/_auth/_characterSidebar/character/roll': {
      preLoaderRoute: typeof AuthCharacterSidebarCharacterRollImport
      parentRoute: typeof AuthCharacterSidebarImport
    }
    '/_auth/explore/character/$id': {
      preLoaderRoute: typeof AuthExploreCharacterIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthCharacterSidebarRoute.addChildren([
      AuthCharacterSidebarCharacterIdRoute,
      AuthCharacterSidebarCharacterRollRoute,
    ]),
    AuthForgingRoute,
    AuthGuildsRoute,
    AuthHomeRoute,
    AuthInventoryRoute,
    AuthMainnavRoute,
    AuthMarketplaceRoute,
    AuthQuestsRoute,
    AuthRankingsRoute,
    AuthTeamfightIdRoute,
    AuthExploreCharacterIdRoute,
  ]),
  LoginRoute,
  NavigationRoute,
])

/* prettier-ignore-end */
