export enum ActionHandler {
  FORAGE = "forage",
  UNFORAGE = "unforage",
  EXPLORE = "explore",
  FIGHT = "fight",
  CONTINUE_EXPLORE = "continue_explore",
  CONTINUE_TEAMFIGHT = "continue_teamfight",
  REVIVE = "revive",
  REBIRTH = "rebirth",
  LVLUP = "lvlup",
  HEAL = "heal",
  LVLDOWN = "lvldown",
  EQUIP = "equip",
  UNEQUIP = "unequip",
}
