export enum ImagePath {
  CHARS = "/img/chars/",
  NEWS = "/img/news/",
  ITEMS = "/img/items/",
  GUILDS = "/img/guilds/",
  DROPS = "/img/drops/",
  CONSUMABLES = "/img/consumables/",
  LOOTS = "/img/loots/",
  BADGES = "/img/badges/",
  WALLPAPER = "/img/wallpaper/",
  GENERAL = "/img/",
  LOGOS = "/img/logos/",
  ICONS = "/img/icons/",
  SLOT = "Icon_EmptySlot.svg",
  PROTAGONISTS = "/img/app/",
  CREEPS = "/img/creeps/",
  EFFECTS = "/img/effects/",
  BACKGROUNDS = "/img/backgrounds/",
  ABILITIES = "/img/abilities/",
  GIFS = "/img/gifs/",
  SOCIAL = "/img/social/",
  STATUSES = "/img/statuses/",
  EVENTS = "/img/events/",
  QUESTS = "/img/quests/",
  SOUNDS = "/sounds/",
  ATTRIBUTES = "/img/attributes/",
}
